GET http://localhost:3030/goals/goals?id=1&month=03&role=employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJodXZhbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE2NTUxOTEwNjR9.sXTGN_axulf6bLHLdWpRxgK2vg6420N-F-FUZPaqf9E

GET http://localhost:3030/goals/goals?id=2&month=03

GET http://localhost:3030/goals/goals?id=3&month=03

POST http://localhost:3030/goals/employee-goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJodXZhbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE2NTUxOTEwNjR9.sXTGN_axulf6bLHLdWpRxgK2vg6420N-F-FUZPaqf9E
Content-Type: application/json

{
    "goal_name": "see the document of redux",
    "status": "pending",
    "date": "2022-03-29",
    "user_id": 1,
    "createdAt":"2022-06-06",
    "updatedAt":"2022-06-06"
}

POST http://localhost:3030/goals/admin-goals
Content-Type: application/json

{
    "goal_name": "interview 2 candidates",
    "status": "completed",
    "date": "2022-1-12",
    "user_id": 2,
    "createdAt":"2022-06-06",
    "updatedAt":"2022-06-06"
}

POST http://localhost:3030/goals/super_admin-goals
Content-Type: application/json

{
    "goal_name": "recruited 2 candidates",
    "status": "completed",
    "date": "2022-1-30",
    "user_id": 3,
    "createdAt":"2022-06-06",
    "updatedAt":"2022-06-06"
}

GET http://localhost:3030/users/users?role=employee

GET http://localhost:3030/users/users?role=admin

POST http://localhost:3030/login
Content-Type: application/json

{
    "email":"user.1@wal.com",
    "password":"user8@89"
}

GET http://localhost:3030/users/gdo?id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJodXZhbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE2NTUxOTEwNjR9.sXTGN_axulf6bLHLdWpRxgK2vg6420N-F-FUZPaqf9E


POST http://localhost:3030/users/users
Content-Type: application/json

{
    "name":"user1",
    "email":"user.1@wal.com",
    "password":"user8@89",
    "mobile":"9879584745",
    "qualification":"B.Tech",
    "role":"employee",
    "gdo":"gdo2",
    "createdAt":"2022-06-03",
    "updatedAt":"2022-06-03"
}

POST http://localhost:3030/users/users
Content-Type: application/json

{
    "name":"user2",
    "email":"user.2@wal.com",
    "password":"user987@1",
    "mobile":"9874551234",
    "qualification":"B.Tech",
    "role":"admin",
    "gdo":"gdo2",
    "createdAt":"2022-06-03",
    "updatedAt":"2022-06-03"
}

POST http://localhost:3030/users/users
Content-Type: application/json

{
    "name":"user3",
    "email":"user.3@wal.com",
    "password":"user987@1",
    "mobile":"8932797389",
    "qualification":"B.Tech",
    "role":"admin",
    "gdo":"gdo1",
    "createdAt":"2022-06-03",
    "updatedAt":"2022-06-03"
}

POST http://localhost:3030/users/users
Content-Type: application/json

{
    "name":"user4",
    "email":"user.4@wal.com",
    "password":"user987@1",
    "mobile":"9874512345",
    "qualification":"B.Tech",
    "role":"employee",
    "gdo":"gdo1",
    "createdAt":"2022-06-03",
    "updatedAt":"2022-06-03"
}

POST http://localhost:3030/users/users
Content-Type: application/json

{
    "name":"user5",
    "email":"user.5@wal.com",
    "password":"user987@1",
    "mobile":"8932797389",
    "qualification":"B.Tech",
    "role":"super_admin",
    "gdo":"gdo",
    "createdAt":"2022-06-03",
    "updatedAt":"2022-06-03"
}

GET http://localhost:3030/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJodXZhbjEyM0BnbWFpbC5jb20iLCJpYXQiOjE2NTUxOTEwNjR9.sXTGN_axulf6bLHLdWpRxgK2vg6420N-F-FUZPaqf9E

DELETE http://localhost:3030/goals/delete?id=10

PUT http://localhost:3030/goals/update 
Content-Type: application/json

{
    "id":7,
    "goal_name":"fitting the employees",
    "status":"failed",
    "updatedAt":"2022-06-08"
}

GET http://localhost:3030/users/gdo-admit?role=admin&gdo=gdo1