GET http://localhost:3000/user/goals?id=1&role=employee

GET http://localhost:3000/user/goals?id=2&role=admin

GET http://localhost:3000/user/goals?id=3&role=super_admin

POST http://localhost:3000/goals/employee
Content-Type: application/json

{
    "goal_name": "successful project delivery",
    "status": "failed",
    "date": "2022-02-28",
    "user_id": 1,
    "createdAt":"2022-06-06",
    "updatedAt":"2022-06-06"
}

POST http://localhost:3000/goals/admin
Content-Type: application/json

{
    "goal_name": "interview 2 candidates",
    "status": "completed",
    "date": "2022-1-12",
    "user_id": 2,
    "createdAt":"2022-06-06",
    "updatedAt":"2022-06-06"
}

POST http://localhost:3000/goals/superadmin
Content-Type: application/json

{
    "goal_name": "recruited 2 candidates",
    "status": "completed",
    "date": "2022-1-30",
    "user_id": 3,
    "createdAt":"2022-06-06",
    "updatedAt":"2022-06-06"
}

GET http://localhost:3000/users/users?role=employee

GET http://localhost:3000/users/users?role=admin

POST http://localhost:3000/
Content-Type: application/json

{
    "email":"user.2@wal.com",
    "password":"user2@202"
}

GET http://localhost:3000/users/gdo?id=2

POST http://localhost:3000/users/users
Content-Type: application/json

{
    "name":"user4",
    "email":"user.4@wal.com",
    "password":"user4@24",
    "mobile":"9765478392",
    "qualification":"MBA",
    "role":"employee",
    "gdo":"gdo1",
    "createdAt":"2022-06-03",
    "updatedAt":"2022-06-03"
}